Argument passing added, errorlog totally revamped

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,53 +17,76 @@ reqs=(dialog reflector dosfstools fzf arch-install-scripts)
 isUEFI=false
 fs=""
 
+read_arguments() {
+    OPTIONS=v
+    LONGOPTS=verbose
+    
+    PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+    eval set -- "$PARSED"
+    verbose=false
+    while true; do
+        case "$1" in
+            -v | --verbose)
+                verbose=true
+                shift
+            ;;
+            --)
+                shift
+                break
+            ;;
+            *)
+                exit 1
+            ;;
+        esac
+    done
+}
 system_check() {
-    [ $EUID -eq 0 ] || (
+    if [ $EUID -ne 0 ]; then
         prompt "This script must be run as root" red
         exit 1
-    )
-
+    fi
+    
     prompt "Checking for internet connection..." yellow
     ping -q -c 1 -W 1 google.com 1>/dev/null || (prompt "No network connection found!" red && exit 1)
     prompt "Internet connection found!" green
-
+    
     prompt "Updating the package database, please be patient..." yellow
-    pacman -Sy 1>/dev/null 2>>$errorfile
+    out true "Pacman" pacman -Sy
     prompt "Updated the package database!" green
-
+    
     prompt "Checking for UEFI..." yellow
     if [ "$(ls -A /sys/firmware/efi/efivars/ 2>/dev/null)" ]; then
         isUEFI=true
         prompt "Found UEFI!" green
     fi
-
+    
     prompt "Identifying GPU drivers..." yellow
     shopt -s nocasematch
     gpus=$(lspci | grep -e VGA -e 3D)
     for gpu in $gpus; do
         case "$gpu" in
-        *"intel"*)
-            prompt "Intel GPU found!" green
-            add_pkg xf86-video-intel
-            add_pkg mesa
-            add_pkg vulkan-intel
-            # HW acceleration
-            add_pkg intel-media-driver
-            add_pkg libva-intel-driver
+            *"intel"*)
+                prompt "Intel GPU found!" green
+                add_pkg xf86-video-intel
+                add_pkg mesa
+                add_pkg vulkan-intel
+                # HW acceleration
+                add_pkg intel-media-driver
+                add_pkg libva-intel-driver
             ;;
-        *"amd"*)
-            prompt "AMD GPU found!" green
-            add_pkg xf86-video-amdgpu
-            add_pkg mesa
-            add_pkg vulkan-radeon
-            # HW acceleration
-            add_pkg libva-mesa-driver
-            add_pkg libva-vdpau-driver
+            *"amd"*)
+                prompt "AMD GPU found!" green
+                add_pkg xf86-video-amdgpu
+                add_pkg mesa
+                add_pkg vulkan-radeon
+                # HW acceleration
+                add_pkg libva-mesa-driver
+                add_pkg libva-vdpau-driver
             ;;
-        *"nvidia"*)
-            prompt "Nvidia GPU found!" green
-            add_pkg nvidia
-            add_pkg nvidia-utils
+            *"nvidia"*)
+                prompt "Nvidia GPU found!" green
+                add_pkg nvidia
+                add_pkg nvidia-utils
             ;;
         esac
     done
@@ -76,9 +99,9 @@ installReqs() {
         reflector --latest 200 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
         prompt "Done generating mirrors" green
     fi
-
+    
     prompt "Installing additional packages if required..." yellow
-    pacman -S "${reqs[@]}" --needed --noconfirm 1>/dev/null 2>>$errorfile
+    out true pacman -S "${reqs[@]}" --needed --noconfirm
 }
 # Get username, hostname, password
 get_config() {
@@ -88,12 +111,12 @@ get_config() {
     locale="$locale".UTF-8
     hostname=$(dialog --inputbox "What hostname would you like?" 8 40 --output-fd 1)
     uName=$(dialog --inputbox "What username would you like?" 8 40 --output-fd 1)
-
+    
     if [[ -z "$uName" || -z "$hostname" ]]; then
         prompt "Username or hostname left blank, try again." red
         get_config
     fi
-
+    
     while true; do
         pass1=$(dialog --passwordbox "What password would you like for ${uName}?" 8 40 --output-fd 1)
         pass2=$(dialog --passwordbox "Confirm password for $uName" 8 40 --output-fd 1)
@@ -110,14 +133,14 @@ get_wm() {
     args=(1 "i3-gaps" off
         2 "KDE plasma" off
         3 "XFCE 4" off
-        4 "No DE/WM" on)
+    4 "No DE/WM" on)
     local choice
     choice=$("${cmd[@]}" "${args[@]}" --output-fd 1)
     clear
     case $choice in
-    1) WM="i3-gaps" ;;
-    2) WM="plasma" ;;
-    3) WM="xfce" ;;
+        1) WM="i3-gaps" ;;
+        2) WM="plasma" ;;
+        3) WM="xfce" ;;
     esac
 }
 
@@ -130,19 +153,19 @@ get_pkgs() {
         4 "PulseAudio" off
         5 "AlsaAudio" off
         6 "NeoVim" off
-        7 "OpenSSH" off)
+    7 "OpenSSH" off)
     local choice
     choices=$("${cmd[@]}" "${args[@]}" --output-fd 1)
     clear
     for i in $choices; do
         case $i in
-        1) add_pkg base-devel ;;
-        2) add_pkg intel-ucode ;;
-        3) add_pkg amd-ucode ;;
-        4) add_pkg pulseaudio ;;
-        5) add_pkg alsa-utils ;;
-        6) add_pkg neovim ;;
-        7) add_pkg openssh ;;
+            1) add_pkg base-devel ;;
+            2) add_pkg intel-ucode ;;
+            3) add_pkg amd-ucode ;;
+            4) add_pkg pulseaudio ;;
+            5) add_pkg alsa-utils ;;
+            6) add_pkg neovim ;;
+            7) add_pkg openssh ;;
         esac
     done
 }
@@ -158,14 +181,14 @@ get_drive() {
     echo
     drives=$(find /dev/sd*[a-z] | sort)
     numDrives=$(echo "$drives" | wc -w)
-
+    
     echo "$drives" | awk '{print NR,$0}'
     while [[ "$choice" -le 0 || "$choice" -gt "$numDrives" ]]; do
         read -r -p "Which drive would you like to install Arch on [1-$numDrives]: " choice
     done
-
+    
     fs=$(echo "$drives" | sed -n "$choice"p)
-
+    
     if [ -z "$fs" ]; then
         prompt "Something went wrong!" red
         exit 1
@@ -174,7 +197,7 @@ get_drive() {
     swap="${fs}"2
     root="${fs}"3
     home="${fs}"4
-
+    
 }
 verify() {
     dialog --title "FINAL CONFIRMATION" --yesno "Username: $uName\nHostname: $hostname\nDE/WM: $WM\nPackages: ${pkgs[*]}\nLocale: $locale\nRoot partition: $rootP\nSwap partition: $swapP\nInstallation drive: $fs\nUEFI enabled: $isUEFI\n" 14 60 || exit
@@ -185,15 +208,15 @@ format_fs() {
     while df | grep -q "$fs"; do
         prompt "$fs seems to be mounted, trying to unmount!" red
         find "$fs"[1-9] | while read -r partition; do
-            umount "$partition" 1>/dev/null 2>>$errorfile
+            out true umount "$partition"
         done
     done
-
+    
     while swapon --show | grep -q "$fs"; do
         prompt "$fs seems to have swap partition, trying to disable it!" red
         swapoff "$(swapon --show | grep "$fs" | awk '{ print $1}')"
     done
-
+    
     prompt "Creating partitions..." yellow
     (
         echo g
@@ -203,24 +226,21 @@ format_fs() {
         mkpart
         echo p
         echo w
-    ) | fdisk "$fs" 1>/dev/null 2>>$errorfile
-
+    ) | out true fdisk "$fs"
+    
     prompt "Formatting partitions..." yellow
-    mkfs.fat -F32 "$bl" 1>/dev/null 2>>$errorfile
-    mkswap "$swap" 1>/dev/null 2>>$errorfile
-    swapon "$swap" 1>/dev/null 2>>$errorfile
-    mkfs.ext4 -F "$root" 1>/dev/null 2>>$errorfile
-    mkfs.ext4 -F "$home" 1>/dev/null 2>>$errorfile
-
+    out true mkfs.fat -F32 "$bl"
+    out true mkswap "$swap"
+    out true swapon "$swap"
+    out true mkfs.ext4 -F "$root"
+    out true mkfs.ext4 -F "$home"
+    
     mount "$root" /mnt
     mkdir /mnt/home
     mount "$home" /mnt/home
-
+    
     # Move errors to the new arch installation
-    cat "$errorfile" >/mnt/"$errorfile"
-    mv /mnt/"$errorfile" /mnt/"$errorfile"/"$uName"/
-    rm -r "$errorfile" &>/dev/null
-
+    mv "$errorfile" /mnt/"$errorfile"
 }
 # sequence for creating a new partition
 mkpart() {
@@ -234,7 +254,7 @@ jumpChroot() {
     printf "locale=\"$locale\"\nuName=\"$uName\"\nuserPass=\"$userPass\"\nhostname=\"$hostname\"\nisUEFI=\"$isUEFI\"\nfs=\"$fs\"\n WM=\"$WM\"\n" >/mnt/CHROOT
     cp "$0" /mnt/install
     chmod 755 /mnt/install
-
+    
     arch-chroot /mnt /bin/bash <<"EOF"
 ./install
 EOF
@@ -247,16 +267,16 @@ arch_install() {
 }
 system_setup() {
     prompt "Setting up the system..." yellow
-    pacman -S --noconfirm --needed networkmanager 1>/dev/null 2>>$errorfile
-    systemctl enable NetworkManager 1>/dev/null 2>>$errorfile
+    out true pacman -S --noconfirm --needed networkmanager
+    out true systemctl enable NetworkManager
     timeZ="$(curl -s "http://worldtimeapi.org/api/ip.txt" | grep timezone | awk '{print $2}')"
-    ln -sf /usr/share/zoneinfo/"$timeZ" /etc/localtime 2>>$errorfile
-    timedatectl set-timezone "$timeZ" 2>>$errorfile
+    out true ln -sf /usr/share/zoneinfo/"$timeZ" /etc/localtime
+    out true timedatectl set-timezone "$timeZ"
     timedatectl set-ntp true
     hwclock --systohc
     sed -i "/$locale/s/^#//g" /etc/locale.gen
     localectl set-locale LANG="$locale"
-    locale-gen 1>/dev/null 2>>$errorfile
+    out true locale-gen
     echo "$hostname" >/etc/hostname
     echo -e "127.0.0.1\t$hostname\n::1\t$hostname\n127.0.1.1\t$hostname.local\t$hostname" >/etc/hosts
     prompt "Finished setting up the system!" green
@@ -270,14 +290,14 @@ user_setup() {
 }
 grub_setup() {
     prompt "Downloading GRUB...." yellow
-    pacman -S --noconfirm grub 1>/dev/null 2>>$errorfile
+    out true pacman -S --noconfirm grub
     if $isUEFI; then
         prompt "Installing and configuring GRUB for UEFI..." yellow
         mkdir /boot/efi
         mount "${fs}"1 /boot/efi
-        pacman -S --noconfirm --needed efibootmgr 1>/dev/null 2>>$errorfile
-        grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi 1>/dev/null 2>>$errorfile
-        grub-mkconfig -o /boot/grub/grub.cfg 1>/dev/null 2>>$errorfile
+        out true pacman -S --noconfirm --needed efibootmgr
+        out true grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi
+        out true grub-mkconfig -o /boot/grub/grub.cfg
         mkdir /boot/efi/EFI/BOOT
         cp /boot/efi/EFI/GRUB/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI
         printf "bcf boot add 1 fs0:\\\EFI\\GRUB\\grubx64.efi\nexit" >/boot/efi/startup.nsh
@@ -286,46 +306,66 @@ grub_setup() {
         prompt "Installing and configuring GRUB for BIOS..." yellow
         mount "${fs}"1 /boot/
         grub-install --target=i386-pc "${fs}"
-        grub-mkconfig -o /boot/grub/grub.cfg 1>/dev/null 2>>$errorfile
+        out true grub-mkconfig -o /boot/grub/grub.cfg
     fi
     umount "${fs}"1
     prompt "Finished configuring GRUB!" green
 }
 wm_setup() {
     userpath=/home/"$uName"/
-
+    
     # Load X resources
     echo "xrdb -load ~/.Xresources &" >"$userpath".xinitrc
-
+    
     prompt "Downloading WM/DE..." yellow
     case "$WM" in
-    i3-gaps)
-        pacman -S --needed --noconfirm i3-gaps rxvt-unicode 1>/dev/null 2>>$errorfile
-        echo "exec i3" >>"$userpath".xinitrc
+        i3-gaps)
+            out true pacman -S --needed --noconfirm i3-gaps rxvt-unicode
+            echo "exec i3" >>"$userpath".xinitrc
         ;;
-    plasma)
-        pacman -S --needed --noconfirm plasma 1>/dev/null 2>>$errorfile
-        echo "exec startplasma-x11" >>"$userpath".xinitrc
+        plasma)
+            out true pacman -S --needed --noconfirm plasma
+            echo "exec startplasma-x11" >>"$userpath".xinitrc
         ;;
-    xfce)
-        pacman -S --needed --noconfirm xfce4 1>/dev/null 2>>$errorfile
-        echo "exec startxfce4" >>"$userpath".xinitrc
+        xfce)
+            out true pacman -S --needed --noconfirm xfce4
+            echo "exec startxfce4" >>"$userpath".xinitrc
         ;;
     esac
     prompt "Finished downloading WM/DE!" green
-
+    
     # Start X server on login if not already running
     printf '[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx' >"$userpath".bash_profile
 }
 prompt() {
     message="$1\033[0m\n"
     case $2 in
-    green) message="\033[1;32m$message" ;;
-    yellow) message="\033[1;33m$message" ;;
-    red) message="\033[1;31m$message" ;;
-    blue) message="\033[1;34m$message" ;;
+        green) message="\033[1;32m$message" ;;
+        yellow) message="\033[1;33m$message" ;;
+        red) message="\033[1;31m$message" ;;
+        blue) message="\033[1;34m$message" ;;
     esac
     printf "$message"
+}
+# Controls where all the text goes
+out() {
+    local logError="$1"
+    shift
+    if $verbose && $logError; then
+        echo "COMMAND: $@" >>$errorfile
+        local lines="$(wc -l < $errorfile)"
+        "$@" 2>>$errorfile
+        [ "$lines" == "$(wc -l < $errorfile)" ] && sed -i '$ d' $errorfile
+        elif $verbose && [ "$logError" == false ]; then
+        "$@"
+        elif [ $verbose == false ] && $logError; then
+        echo "COMMAND: $@" >>$errorfile
+        local lines="$(wc -l < $errorfile)"
+        "$@" 1>/dev/null 2>>$errorfile
+        [ "$lines" == "$(wc -l < $errorfile)" ] && sed -i '$ d' $errorfile
+    else
+        "$@" >/dev/null 2>&1
+    fi
 }
 if ls CHROOT &>/dev/null; then
     source CHROOT
@@ -338,6 +378,7 @@ if ls CHROOT &>/dev/null; then
     fi
 else
     clear
+    read_arguments "$@"
     prompt "Running in non chrooted mode!" green
     system_check
     rm -f "$errorfile"
